Moving Mac architecture detection so that it applies to all requests.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -18,6 +18,19 @@ install_MySQL() {
       FILE="mysql-${version}-linux*$(uname -m)*"
       ;;
     Darwin)
+      case "$(uname -m)" in
+        i386|x86_64)
+          ARCH="x86_64"
+          ;;
+        *)
+          ARCH="arm64"
+          if (( ${MAJOR} < 8 )) || (( (( ${MAJOR} == 8 )) && (( ${PATCH} <= 25 )) )); then
+            echo "Error: pre-built binaries are not available for ARM prior to 8.0.26"
+            exit 1
+          fi
+          ;;
+      esac
+
       if (( ${MAJOR} < 5 )); then
           echo "Error: Mysql v4.x and earlier are not supported on OS X"
           exit 1
@@ -25,19 +38,6 @@ install_MySQL() {
         # the mirrorservice listings for mysql-8.0 have updated to list macos11 as the OS association
         FILE="mysql-${version}.*"
       else
-        case "$(uname -m)" in
-          i386|x86_64)
-            ARCH="x86_64"
-            ;;
-          *)
-            ARCH="arm64"
-            if (( ${MAJOR} < 8 )) || (( (( ${MAJOR} == 8 )) && (( ${PATCH} <= 25 )) )); then
-              echo "Error: pre-built binaries are not available for ARM prior to 8.0.26"
-              exit 1
-            fi
-            ;;
-        esac
-
         MACOSVER="11"
         if (( ${MAJOR} >= 8 )) && (( ${PATCH} >= 29 )); then
           MACOSVER="12"
